### PR TITLE
update notebooks

### PR DESCRIPTION
**Pull request by clewis7**
align notebooks with `fastplotlib` changes

#213

### CODE REVIEW

**Comment by kushalkolar** [comment]
@clewis7 can you confirm that these work with latest fpl from pip? There are users searching the docs for the old line slider numerous times so we really need to merge this.

**Comment by kushalkolar** [comment]
not sure why build failed, might have been an issue in something upstream last month, _probably_ caiman. Did a minor commit to trigger CI.

**Comment by kushalkolar** [comment]
we are getting the weirdest build failures.

The conda installs don't work becaues mamba is being weird.

linux: https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218

```
mamba env update -n base --file environment.yml
  caimanmanager.py install
  pip install .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:3).10.12/x6[4](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.12/x64/lib


Looking for: ["caiman[version='>=1.9.10']", "pandas[version='>=1.[5](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:5).0']", 'requests', 'click', 'jupyterlab', 'tqdm', 'psutil']


warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
Could not solve for environment specs
The following packages are incompatible
└─ caiman >=1.9.10  is installable with the potential options
   ├─ caiman [1.9.10|1.9.11|...|1.9.15] would require
   │  └─ python >=3.10,<3.11.0a0 , which can be installed;
   ├─ caiman [1.9.10|1.9.11|...|1.9.15] would require
   │  └─ python >=3.[8](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:8),<3.[9](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:10).0a0 , which can be installed;
   └─ caiman [1.9.[10](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:11)|1.9.[11](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:12)|...|1.9.[15](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262161/job/16243264758?pr=218#step:6:16)] would require
      └─ python >=3.9,<3.10.0a0 , which can be installed.
```

MacOS: https://github.com/nel-lab/mesmerize-core/actions/runs/5988262158/job/16243264691?pr=218

```
Run mamba env update -n base --file environment.yml
  mamba env update -n base --file environment.yml
  caimanmanager.py install
  pip install .
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.10.1[2](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262158/job/16243264691?pr=218#step:6:2)/x64
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/usr/local/miniconda/lib/python[3](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262158/job/16243264691?pr=218#step:6:3).11/site-packages/mamba/mamba.py", line [4](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262158/job/16243264691?pr=218#step:6:4)9, in <module>
    import libmambapy as api
  File "/usr/local/miniconda/lib/python3.11/site-packages/libmambapy/__init__.py", line [7](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262158/job/16243264691?pr=218#step:6:7), in <module>
    raise e
  File "/usr/local/miniconda/lib/python3.[11](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262158/job/16243264691?pr=218#step:6:12)/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/usr/local/miniconda/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded: '@rpath/libarchive.[13](https://github.com/nel-lab/mesmerize-core/actions/runs/5988262158/job/16243264691?pr=218#step:6:14).dylib'
  Referenced from: '/usr/local/miniconda/lib/libmamba.2.0.0.dylib'
  Reason: tried: '/usr/local/miniconda/lib/libarchive.13.dylib' (no such file), '/usr/local/miniconda/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/miniconda/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/miniconda/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/miniconda/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)
```

The pip install runs, but weird issue with running CNMFE:

https://github.com/nel-lab/mesmerize-core/actions/runs/5988262157/job/16243264692?pr=218#step:7:1541

```python
E           Traceback (most recent call last):
E             File "/home/runner/work/mesmerize-core/mesmerize-core/mesmerize_core/algorithms/cnmfe.py", line 89, in run_algo
E               cnm = cnm.fit(images)
E             File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 594, in fit
E               self.estimates.sn, self.estimates.optional_outputs = run_CNMF_patches(
E             File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 476, in run_CNMF_patches
E               B_tot = np.array(B_tot, dtype=np.float32)
E           TypeError: float() argument must be a string or a number, not 'coo_matrix'
```

**Comment by clewis7** [comment]
I don't know why the build is failing, but the notebooks worked on my end in a fresh environment with latest pip install of fpl, caiman, and mescore

**Pull request merged**
